### ISSUE TITLE
calculateInSampleSize generates bitmaps smaller than required.

### ISSUE THREAD

**Issue by kovarn** [googlesamples/android-DisplayingBitmaps#6]
The logic here is wrong. `inSampleSize` applies scaling to the height and the width of the bitmap, 
and so the number of pixels should be scaled by the square of `inSampleSize`.

[ImageResizer.java#L251](https://github.com/googlesamples/android-DisplayingBitmaps/blob/40cdd426a4b9439ae72d688458bab7f97743d06f/Application/src/main/java/com/example/android/displayingbitmaps/util/ImageResizer.java#L251)
```java
    // This offers some additional logic in case the image has a strange
    // aspect ratio. For example, a panorama may have a much larger
    // width than height. In these cases the total pixels might still
    // end up being too large to fit comfortably in memory, so we should
    // be more aggressive with sample down the image (=larger inSampleSize).

    long totalPixels = width * height / inSampleSize;

    // Anything more than 2x the requested pixels we'll sample down further
    final long totalReqPixelsCap = reqWidth * reqHeight * 2;

    while (totalPixels > totalReqPixelsCap) {
    inSampleSize *= 2;
    totalPixels /= 2;
    }
```
This causes generated bitmaps to be of much lower size than required.

**Comment by adamkoch** [comment]
Good catch, it should indeed be divided by the square of inSampleSize. This sample is being reviewed right now to see what updates (or not) will be made.

As a side note, outside of understanding how these APIs work, if you are trying to load images in a real app, we highly recommend using a well tested image loading library such as Glide (https://github.com/bumptech/glide) or Picasso (http://square.github.io/picasso/).

**Comment by yglx** [comment]
when I add an 3M picture url and  open the some ImageDetailActivity frequently,log shows
`com.example.android.displayingbitmaps E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
    java.lang.Throwable: Explicit termination method 'close' not called
        at dalvik.system.CloseGuard.open(CloseGuard.java:223)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:224)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
        at com.example.android.displayingbitmaps.util.DiskLruCache$Editor.newOutputStream(DiskLruCache.java:819)
        at com.example.android.displayingbitmaps.util.ImageFetcher.processBitmap(ImageFetcher.java:215)
        at com.example.android.displayingbitmaps.util.ImageFetcher.processBitmap(ImageFetcher.java:257)
        at com.example.android.displayingbitmaps.util.ImageWorker$BitmapWorkerTask.doInBackground(ImageWorker.java:312)
        at com.example.android.displayingbitmaps.util.ImageWorker$BitmapWorkerTask.doInBackground(ImageWorker.java:257)
        at com.example.android.displayingbitmaps.util.AsyncTask$2.call(AsyncTask.java:313)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)`
how it happened

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
